package com.dose.packattack.enumerate;

public enum ETexture {
	BACKGROUND, POPAP_BACKGROUND, LAYER_1, LAYER_2, THREE,
	PLAYER_STAY,	PLAYER_1,	PLAYER_2,	PLAYER_3,	PLAYER_4,	PLAYER_5,	PLAYER_6, PLAYER_7, PLAYER_8,
	PLAYER_MOVE_1,	PLAYER_MOVE_2,	PLAYER_MOVE_3,	PLAYER_MOVE_4,
	PLAYER_MOVE_5,	PLAYER_MOVE_6,	PLAYER_MOVE_7,	PLAYER_MOVE_8,
	
	PELICAN_1,	PELICAN_2,	PELICAN_3,	PELICAN_4,
	CUBE_WOOD, CUBE_METAL, HEART, 
	DIGITAL_1,	DIGITAL_2,	DIGITAL_3,	DIGITAL_4,	DIGITAL_5,
	DIGITAL_6,	DIGITAL_7,	DIGITAL_8,	DIGITAL_9,	DIGITAL_0,
}
