package com.dose.packattack.enumerate;

public enum ETexture {
	BACKGROUND, POPAP_BACKGROUND,
	PLAYER_0,	PLAYER_1,	PLAYER_2,	PLAYER_3,	PLAYER_4,	PLAYER_5,	PLAYER_6,
	PELICAN_1,	PELICAN_2,	PELICAN_3,	PELICAN_4,
	CUBE_WOOD, 
	DIGITAL_1,	DIGITAL_2,	DIGITAL_3,	DIGITAL_4,	DIGITAL_5,
	DIGITAL_6,	DIGITAL_7,	DIGITAL_8,	DIGITAL_9,	DIGITAL_0,
}
